### ISSUE TITLE
you used a 5x9 square grid

### ISSUE THREAD

**Issue by george-tsiros** [weirdoonthebus/Kepler-452b#2] opened 2022-07-29 21:23 UTC
yes? :>

btw, one of my favorite fonts, ever

sadly, visual studio refuses to use it

thankfully, legacy command prompt accepts it!

(it not an issue!)

**Comment by george-tsiros** [comment] 2022-08-02 06:07
I can't fit it in a 5x9 grid... I am hesitant to up it to 9x17 even though there is nothing that prevents me from it

(i am trying to convert the font glyphs to line segments connecting points on a square grid)

**Comment by weirdoonthebus** [comment] 2023-08-31 23:16
Apologies, I'm still very new to font design, and I'm not sure what the issue is here.. I'd be happy to fix it though, could you provide a bit more info as to how I should go about it?

**Comment by george-tsiros** [comment] 2023-08-31 23:21
Nono! There is no issue! I was trying to convert each glyph to line segments (for my own personal use, I have not and will not make anything public) .

**Comment by weirdoonthebus** [comment] 2023-08-31 23:36
Oh ok! I'll just close the issue then. Btw the font license does allow for modifications and such, I wouldn't be bothered if you had released it.

**Closed as completed by weirdoonthebus** 2023-08-31 23:36 UTC
